module.exports = [
  {
    //this confirm works
    hotelId: 1,
    hotelName: "Conrad Centennial Singapore",
    hotelImg: "",
    location: "Marina Bay",
    address: "Two Temasek Boulevard, Marina Bay, 038982 Singapore",
    geolocation: {
      longitude: 103.8587261,
      latitude: 1.2934379,
    },
    hotelRating: 4.9,
    vacancies: true,
    feedback: [
      {
        username: "Jasmine",
        userRating: 9.6,
        userFeedback: "Good staycation option",
      },
      {
        username: "Nicolaas",
        userRating: 10,
        userFeedback: "Excellent staycation weekend !",
      },
      {
        username: "Swee",
        userRating: 9.0,
        userFeedback:
          "Fantastic service and experience, although slightly pricey",
      },
      {
        username: "Patrick",
        userRating: 10,
        userFeedback: "have a wonderful stay in a luxurious hotel",
      },
      {
        username: "Rajan",
        userRating: 10,
        userFeedback:
          "Fantastic service and experience, although slightly pricey",
      },
      {
        username: "Norman",
        userRating: 8.0,
        userFeedback: "we had enjoyable time staying at Conrad",
      },
      {
        username: "Lee",
        userRating: 8.0,
        userFeedback: "Very good",
      },
      {
        username: "Cheryl",
        userRating: 8.0,
        userFeedback: "Is an enjoyable stay in Conrad",
      },
    ],
    amenities: [
      "Swimming Pool",
      "Free Wifi",
      "Non-Smoking Rooms",
      "Free Parking",
      "Bar",
      "Gym",
    ],
    userStayed: [
      "Jasmin",
      "Cheryl",
      "Lee",
      "Rajan",
      "Patrick",
      "Swee",
      "Nicolaas",
    ],
    roomsGeneral: [
      {
        roomType: "Deluxe",
        maxPax: 2,
        price: 450,
        roomImg: "",
        size: "40 sqf",
        amenities: ["Minibar", "Safe Deposit Box", "Closet"],
      },
      {
        roomType: "Grand Deluxe",
        maxPax: 3,
        price: 600,
        roomImg: "",
        size: "55sqf",
        amenities: [
          "Minibar",
          "Safe Deposit Box",
          "Closet",
          "Bathtub",
          "Coffee Machine",
        ],
      },
      {
        roomType: "Suite",
        maxPax: 4,
        price: 1000,
        roomImg: "",
        size: "55sqf",
        amenities: [
          "Minibar",
          "Safe Deposit Box",
          "Closet",
          "Bathtub",
          "Coffee Machine",
          "Wake up service/Alarm clock",
          "Butler Service",
        ],
      },
    ],
  },
  {
    hotelId: 2,
    hotelName: "Co4324d Centennial Singapore",
    hotelImg: "",
    location: "Marina Bay",
    address: "Two Temasek Boulevard, Marina Bay, 038982 Singapore",
    geolocation: {
      longitude: 103.8587261,
      latitude: 1.2934379,
    },
    hotelRating: 4.9,
    vacancies: true,
    feedback: [
      {
        username: "Jasmine",
        userRating: 9.6,
        userFeedback: "Good staycation option",
      },
      {
        username: "Nicolaas",
        userRating: 10,
        userFeedback: "Excellent staycation weekend !",
      },
      {
        username: "Swee",
        userRating: 9.0,
        userFeedback:
          "Fantastic service and experience, although slightly pricey",
      },
      {
        username: "Patrick",
        userRating: 10,
        userFeedback: "have a wonderful stay in a luxurious hotel",
      },
      {
        username: "Rajan",
        userRating: 10,
        userFeedback:
          "Fantastic service and experience, although slightly pricey",
      },
      {
        username: "Norman",
        userRating: 8.0,
        userFeedback: "we had enjoyable time staying at Conrad",
      },
      {
        username: "Lee",
        userRating: 8.0,
        userFeedback: "Very good",
      },
      {
        username: "Cheryl",
        userRating: 8.0,
        userFeedback: "Is an enjoyable stay in Conrad",
      },
    ],
    amenities: [
      "Swimming Pool",
      "Free Wifi",
      "Non-Smoking Rooms",
      "Free Parking",
      "Bar",
      "Gym",
    ],
    userStayed: [
      "Jasmin",
      "Cheryl",
      "Lee",
      "Rajan",
      "Patrick",
      "Swee",
      "Nicolaas",
    ],
    roomsGeneral: [
      {
        roomType: "Deluxe",
        maxPax: 2,
        price: 450,
        roomImg: "",
        size: "40 sqf",
        amenities: ["Minibar", "Safe Deposit Box", "Closet"],
      },
      {
        roomType: "Grand Deluxe",
        maxPax: 3,
        price: 600,
        roomImg: "",
        size: "55sqf",
        amenities: [
          "Minibar",
          "Safe Deposit Box",
          "Closet",
          "Bathtub",
          "Coffee Machine",
        ],
      },
      {
        roomType: "Suite",
        maxPax: 4,
        price: 1000,
        roomImg: "",
        size: "55sqf",
        amenities: [
          "Minibar",
          "Safe Deposit Box",
          "Closet",
          "Bathtub",
          "Coffee Machine",
          "Wake up service/Alarm clock",
          "Butler Service",
        ],
      },
    ],
  },
  {
    hotelId: 3,
    hotelName: "Conrad Centennial Singapore",
    hotelImg: "",
    location: "Marina Bay",
    address: "Two Temasek Boulevard, Marina Bay, 038982 Singapore",
    geolocation: {
      longitude: 103.8587261,
      latitude: 1.2934379,
    },
    hotelRating: 4.9,
    vacancies: true,
    feedback: [
      {
        username: "Jasmine",
        userRating: 9.6,
        userFeedback: "Good staycation option",
      },
      {
        username: "Nicolaas",
        userRating: 10,
        userFeedback: "Excellent staycation weekend !",
      },
      {
        username: "Swee",
        userRating: 9.0,
        userFeedback:
          "Fantastic service and experience, although slightly pricey",
      },
      {
        username: "Patrick",
        userRating: 10,
        userFeedback: "have a wonderful stay in a luxurious hotel",
      },
      {
        username: "Rajan",
        userRating: 10,
        userFeedback:
          "Fantastic service and experience, although slightly pricey",
      },
      {
        username: "Norman",
        userRating: 8.0,
        userFeedback: "we had enjoyable time staying at Conrad",
      },
      {
        username: "Lee",
        userRating: 8.0,
        userFeedback: "Very good",
      },
      {
        username: "Cheryl",
        userRating: 8.0,
        userFeedback: "Is an enjoyable stay in Conrad",
      },
    ],
    amenities: [
      "Swimming Pool",
      "Free Wifi",
      "Non-Smoking Rooms",
      "Free Parking",
      "Bar",
      "Gym",
    ],
    userStayed: [
      "Jasmin",
      "Cheryl",
      "Lee",
      "Rajan",
      "Patrick",
      "Swee",
      "Nicolaas",
    ],
    rooms: [{ inDate: "02/10/21", outDate: "05/10/21", roomType: "Deluxe"}],
    roomsGeneral: [
      {
        roomType: "Deluxe",
        maxPax: 2,
        price: 450,
        roomImg: "",
        size: "40 sqf",
        amenities: ["Minibar", "Safe Deposit Box", "Closet"],
      },
      {
        roomType: "Grand Deluxe",
        maxPax: 3,
        price: 600,
        roomImg: "",
        size: "55sqf",
        amenities: [
          "Minibar",
          "Safe Deposit Box",
          "Closet",
          "Bathtub",
          "Coffee Machine",
        ],
      },
      {
        roomType: "Suite",
        maxPax: 4,
        price: 1000,
        roomImg: "",
        size: "55sqf",
        amenities: [
          "Minibar",
          "Safe Deposit Box",
          "Closet",
          "Bathtub",
          "Coffee Machine",
          "Wake up service/Alarm clock",
          "Butler Service",
        ],
      },
    ],
  },
];
